### ISSUE TITLE
labelling layers

### ISSUE THREAD

**Issue by sp4ceman** [OFFLINE-GmbH/multi-timeline.js#1]
hey there, awesome awesome library. 
i was just wondering is there an easy way to provide a "label" for each layer? so that if you have several items on the same layer you can provide some sort of context for it to the side of the control, that stays in position as the timeline is scrolled.

**Comment by tobias-kuendig** [comment]
Unfortunately there is no such feature available at the moment.

If you need this functionality you may want to look into somethingn like the FullCalendar Scheduler: http://fullcalendar.io/scheduler/
