### ISSUE TITLE
Just a question : add event markers within a timeline

### ISSUE THREAD

**Issue by cretace** [OFFLINE-GmbH/multi-timeline.js#4]
Hi
I need to add event markers on specific dates within my timelines.
Each timeline is a 'project' on its own row, and each project will have maybe 10 key events that I'll indicate with a diamond - on rollover a tooltip will show the named event.

Do you think this should be fairly easy for me to figure out and build ?
I'm not a JS expert but not a beginner either.
I can always send you my hacky code when it's done!

I looked at vis.js but it seems bad at overlaying multiple timelines.

ALSo - on your demos, mousewheel only moves the chart to the left - reverse mousewheel does not move it back ?
Thanks!

**Comment by tobias-kuendig** [comment]
I'd start by adding a `markers` array to the `data` property of the timeline and then work from there. It shouldn't be that complicated, but I guess you'll need some time to grasp how the plugin works.

Just fork the project and give it a try. As you said, PRs with new features are always welcome.

The bug with the mouse wheel has been moved to #5, thanks for pointing that out.
